apiVersion: v1
kind: ReplicationController
metadata:
  name: hola-rc
spec:
  replicas: 15
  selector:
    app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: hola-pod
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080