apiVersion: v1
kind: Service
metadata:
  name: hola-svc
  labels:
    app: hola-mundo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
    protocol: TCP
  selector:
    app: hola-mundo